dist: xenial
language: python
python:
    - "3.7"

install:
    - pip install --user travis-sphinx sphinx-rtd-theme

script:
    - git clone https://github.com/LamininSolutions/MFSQLConnector
    - find MFSQLConnector -name '*.sql' -exec python doc_extractor.py {} \;
    - travis-sphinx build --source=./source

after_success:
    travis-sphinx deploy
